import glob
import os
import shutil
import subprocess
import tempfile

# Paths
input_dir = os.path.expanduser("/Users/ishaan/Documents/Comics:Mangas/ultimateFF-temp")
output_dir = os.path.expanduser('/Users/ishaan/Documents/Comics:Mangas/Ultimate Universe/Ultimate FF')
#os.makedirs(output_dir, exist_ok=True)

# Collect all EPUB / KEPUB files in the directory
files = glob.glob(os.path.join(input_dir, "*.epub")) + glob.glob(
    os.path.join(input_dir, "*.kepub.epub")
)

if not files:
  print(f"No .epub or .kepub.epub files found in: {input_dir}")
  exit(0)

print(f"Found {len(files)} file(s) to process.\n")

for file_path in files:
  filename = os.path.basename(file_path)

  # Ignore hidden files generated by macOS
  if filename.startswith("._"):
    continue

  print(f"Processing: {filename}...")
  temp_dir = tempfile.mkdtemp()

  try:
    # 1. Extract the EPUB/KEPUB archive
    subprocess.run(["unzip", "-q", file_path, "-d", temp_dir], check=True)

    # 2. Gather all image files
    img_files = []
    for root, _, filenames in os.walk(temp_dir):
      for f in filenames:
        if f.lower().endswith((".jpg", ".jpeg", ".png", ".webp")):
          img_files.append(os.path.join(root, f))

    # 3. Apply ImageMagick adjustments in-place
    if img_files:
      print(f"  -> Enhancing {len(img_files)} images...")
      cmd = [
          "magick",
          "mogrify",
          "-modulate",
          "100,125,100",
          "-sigmoidal-contrast",
          "3x50%",
          "-unsharp",
          "0x0.75+0.75+0.008",
      ] + img_files
      subprocess.run(cmd, check=True)

    # 4. Repackage into a clean KEPUB/EPUB file
    out_path = os.path.join(output_dir, filename)
    if os.path.exists(out_path):
      os.remove(out_path)

    mimetype_file = os.path.join(temp_dir, "mimetype")
    if os.path.exists(mimetype_file):
      # mimetype must be first and uncompressed for valid EPUB compliance
      subprocess.run(
          ["zip", "-q", "-X0", out_path, "mimetype"], cwd=temp_dir, check=True
      )
      subprocess.run(
          ["zip", "-q", "-rg", out_path, ".", "-x", "*.DS_Store", "mimetype"],
          cwd=temp_dir,
          check=True,
      )
    else:
      subprocess.run(
          ["zip", "-q", "-r", out_path, ".", "-x", "*.DS_Store"],
          cwd=temp_dir,
          check=True,
      )

    print(f"Finished: {filename}\n")

  except Exception as e:
    print(f"Error processing {filename}: {e}\n")

  finally:
    # Clean up temporary working directory
    shutil.rmtree(temp_dir)

print(f"All processing complete! Files saved to:\n{output_dir}")